# Generated by Django 2.0.4 on 2018-05-04 15:34

from django.db import migrations
import os
from django.contrib.gis.utils import LayerMapping
from ..models import province_mapping, region_mapping, country_mapping


def run(apps, schema_editor):
    Country = apps.get_model('scrape', 'Country')
    Province = apps.get_model('scrape', 'Province')
    Region = apps.get_model('scrape', 'Region')

    country_shp = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../' 'data', 'NLD_adm', 'NLD_adm0.shp'),
    )

    province_shp = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../', 'data', 'NLD_adm', 'NLD_adm1.shp'),
    )

    region_shp = os.path.abspath(
        os.path.join(os.path.dirname(__file__),  '../', 'data', 'NLD_adm', 'NLD_adm2.shp'),
    )
    ct = LayerMapping(
        Country, country_shp, country_mapping,
        transform=False, encoding='iso-8859-1',
    )
    ct.save(strict=True, verbose=True)

    pr = LayerMapping(
        Province, province_shp, province_mapping,
        transform=False, encoding='iso-8859-1',
    )
    pr.save(strict=True, verbose=True)


    rg = LayerMapping(
        Region, region_shp, region_mapping,
        transform=False, encoding='iso-8859-1',
    )
    rg.save(strict=True, verbose=True)



class Migration(migrations.Migration):
    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run),
    ]
