version: '3.4'
services:
    vpn-client:
        image: bubuntux/nordvpn
        container_name: vpn-client
        cap_add:
            - net_admin
        env_file:
            - .env # make sure it contains USER and PASS
        devices:
            - '/dev/net/tun'
        tmpfs:
            - /tmp
        restart: unless-stopped
        stdin_open: true
        tty: true
    foursquare:
        build: ./foursquare
        volumes: 
            - data:/foursquare/output
        command: python main.py
    fundanl:
        build: ./fundanl
        env_file:
            - .env
        links:
            - postgres
        command: python main.py
    pararius:
        build: ./pararius
        container_name: pararius
        depends_on:
            - vpn-client
        #links:
        #    - postgres
        network_mode: "service:vpn-client"
        stdin_open: true
        tty: true
        command: sh #python main.py
    postgres:
        image: mdillon/postgis:latest
        container_name: postgres
        env_file:
            - .env # make sure it contains POSTGRES_USER, POSTGRES_DB and POSTGRES_PASSWORD
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
    rabbitmq:
        image: rabbitmq:3.7-rc-management
        container_name: rabbitmq
        env_file:
            - .env
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
    worker:
        build: ./worker_app
        container_name: worker_app
        #command: celery -A worker_app worker --concurrency=5 --loglevel=info
        env_file:
            - .env
        links:
            - rabbitmq
            - postgres
        depends_on:
            - rabbitmq
            - postgres
        tty: true
    data:
        image: busybox:latest
        volumes:
            - data:/data
volumes:
    data: 
        external: true
        name: scrape_data
    postgres_data: 
        external: true
        name: postgres_data