version: '3.4'
services:
    foursquare:
        build: ./foursquare
        volumes: 
            - data:/foursquare/output
        command: python main.py
    fundanl:
        build: ./fundanl
        volumes:
            - data:/fundanl/output
        links:
            - postgres
        command: python main.py
    pararius:
        build: ./pararius
        volumes:
            - data:/pararius/output
        links:
            - postgres
        command: python main.py
    postgres:
        image: mdillon/postgis:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=nl-scrape
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
    data:
        image: busybox:latest
        volumes:
            - data:/data
volumes:
    data: 
        external: true
        name: scrape_data
    postgres_data: 
        external: true
        name: postgres_data
